const tintColor = '#2f95dc';

export default {
  tintColor,
  tabIconDefault: '#ccc',
  tabIconSelected: tintColor,
  tabBar: '#fefefe',
  errorBackground: 'red',
  errorText: '#fff',
  warningBackground: '#EAEB5E',
  warningText: '#666804',
  noticeBackground: tintColor,
  noticeText: '#fff',
  primary: '#f1544d',
  primaryDark: '#c94740',
  text: '#fff',
  accent: '#f0d04c',
  grey: '#888',
  darkGrey: '#333',
  lightGrey: '#eee',
  white: '#fff',
  black: '#000',
  fadedBlack: 'rgba(0, 0, 0, .5)',
  backgroundColor: "#f2f2f2",
};
