name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: Setup Yarn (v2 or later using Corepack)
        run: |
          corepack enable
          corepack prepare yarn@4.4.1 --activate
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          yarn



